from datetime import date
from dateutil.relativedelta import relativedelta
from google.appengine.ext import ndb

"""  PromoCodes are generated by Lemmiwink.
    Each user also has a referral code to share.
"""

class PromoCode(ndb.Model):
    code = ndb.StringProperty(required=True)
    user = ndb.KeyProperty()    # attached to user?
    amount = ndb.FloatProperty(default=0.00)
    expires = ndb.DateProperty()

    def _pre_put_hook(self):
        #if self.key is None:  # first put
        # check for dups
        c = PromoCode.query(PromoCode.code==self.code).get()
        if c:
            return
        self.expires = date.today() + relativedelta(months=3)

    @classmethod
    def by_code(cls,code):
        return cls.query(cls.code==code).get()

    """User's individual referral code"""
    @classmethod
    def by_user(cls,key):
        return cls.query(cls.user==key).get()

    @classmethod
    def valid_code(cls,code):
        c = cls.query(cls.code==code).get()
        if c and c.expires >= date.today():
            return c
        return False
